### PR TITLE
Added "--no-check-certificate" to wget

### PR DESCRIPTION
**Pull request by martijngonlag**

### CODE REVIEW

**Comment by grittygrease** [comment]
Why is this being added?

**Comment by martijngonlag** [comment]
Without it, the mod_cloudflare script fails:

```
--2015-10-15 01:08:16--  https://raw.githubusercontent.com/cloudflare/mod_cloudflare/master/mod_cloudflare.c
Resolving raw.githubusercontent.com... 23.235.44.133
Connecting to raw.githubusercontent.com|23.235.44.133|:443... connected.
ERROR: certificate common name `www.github.com' doesn't match requested host name `raw.githubusercontent.com'.
To connect to raw.githubusercontent.com insecurely, use `--no-check-certificate'.
Unable to establish SSL connection.
tar: mod_cloudflare/mod_cloudflare.c: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors
--2015-10-15 01:08:16--  https://raw.githubusercontent.com/cloudflare/mod_cloudflare/master/EasyApache/ModCloudflare.pm
Resolving raw.githubusercontent.com... 23.235.44.133
Connecting to raw.githubusercontent.com|23.235.44.133|:443... connected.
ERROR: certificate common name `www.github.com' doesn't match requested host name `raw.githubusercontent.com'.
To connect to raw.githubusercontent.com insecurely, use `--no-check-certificate'.
Unable to establish SSL connection.
```

Is there a better way to work around this that  would be preferred?

**Comment by miohtama** [comment]
"--no-check-certificate" is not a great idea in security sensitive software.

Instead, try to address the root cause - why don't you have root certificates on your server in the first place? Common root certificates should be included in `ca-certificates` in Ubuntu package: https://launchpad.net/ubuntu/+source/ca-certificates and other operating systems have corresponding packages.

There have been some issues in the past where Github root certificate was not included (DigiCert?), but as far as I see it has been fixed years ago.

Below is from Ubuntu 14.04 and it shows wget works:

    wget "https://raw.githubusercontent.com/cloudflare/mod_cloudflare/master/mod_cloudflare.c"
    --2015-10-17 04:01:48--  https://raw.githubusercontent.com/cloudflare/mod_cloudflare/master/mod_cloudflare.c
    Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 23.235.47.133
    Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|23.235.47.133|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 20493 (20K) [text/plain]

**Comment by HostOnNet** [comment]
Works CloudLinux 6.7 too

```
# wget "https://raw.githubusercontent.com/cloudflare/mod_cloudflare/master/mod_cloudflare.c"
--2015-10-17 04:05:19--  https://raw.githubusercontent.com/cloudflare/mod_cloudflare/master/mod_cloudflare.c
Resolving raw.githubusercontent.com... 23.235.44.133
Connecting to raw.githubusercontent.com|23.235.44.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20493 (20K) [text/plain]
Saving to: “mod_cloudflare.c”

100%[===================================================================================================================================================================>] 20,493      --.-K/s   in 0.01s   

2015-10-17 04:05:19 (1.47 MB/s) - “mod_cloudflare.c” saved [20493/20493]

# cat /etc/*release
CloudLinux Server release 6.7 (Aleksei Gubarev)
CloudLinux Server release 6.7 (Aleksei Gubarev)
# 
```

**Pull request closed without merging**
